DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'players'::regclass
      AND attname = 'id'
      AND attidentity <> ''
  ) THEN
    ALTER TABLE players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END;
$$;

SELECT setval(
  pg_get_serial_sequence('players', 'id'),
  COALESCE((SELECT MAX(id) FROM players), 1),
  EXISTS (SELECT 1 FROM players)
);
